FROM ros:noetic-ros-core-focal

ENV WS_DIR="/ros_ws"

#SHELL ["/bin/bash", "-c"]

RUN apt-get update \
 && apt-get install -y \
    build-essential \
    cmake \
    git-all \
    software-properties-common \
 && rm -rf /var/lib/apt/lists/*

# Install dependencies: See https://github.com/IntelRealSense/realsense-ros/tree/ros2-development
# Librealsense: See https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages
RUN apt-get update \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \
 && add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u \
 && apt-get install -y \
    librealsense2-dkms \
    librealsense2-utils \
    librealsense2-dev \
    librealsense2-dbg

RUN apt-get update \
 && apt-get install -y \
    ros-noetic-rviz \
    python3 pip \
 && pip3 install -U rosdep \
 && rosdep init \
 && rosdep update 

WORKDIR ${WS_DIR}/src
RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
 && catkin_init_workspace \
 && cd .. \
 && catkin_make

RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
 && . ${WS_DIR}/devel/setup.sh \
 && git clone https://github.com/IntelRealSense/realsense-ros.git -b ros1-legacy \
 && cd .. \
 && rosdep install -r --from-path src --rosdistro ${ROS_DISTRO} --skip-keys=librealsense2 -y \
 && catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
 
